### ISSUE TITLE
You can Plonk entities that you are holding with CarryOn

### ISSUE THREAD

**Issue by Alexander3847575** [breakinblocks/Plonk#13]
Steps to reproduce:
Install CarryOn and Plonk
Carry a (tile)entity
plonk

a member of my server found that you can plonk it onto a hopper and it will pick up the entity. when a tileentity containing a carryon entity item is broken is survival, all entities are placed back into the world. no dupe glitches have been found yet.
this should be fixable by adding a blacklist of items you cannot plonk, and simply adding carryon:* to it.

not game breaking yet, but

**Comment by BlueAgent** [comment]
Oooh intersting, so CarryOn probably implements stuff you're carrying around as an item stack.

This is a pretty neat interaction though, I do kinda like the idea of breaking a block and a bunch of mobs flying out of it. XD

I've noticed some other interesting interactions while testing.
If you use the toolbelt mod, you can put the held mob into the toolbelt as well and store it for later.

~~I think something I should be checking is if an item can be removed from an inventory slot before it gets placed down, which I'm assuming CarryOn will cancel / prevent may fix it?~~ Nvm it doesn't.

However the config option would be better for general case so I will do that.

**Comment by BlueAgent** [comment]
Added in [Plonk v9.0.8 (mc 1.16.5)](https://www.curseforge.com/minecraft/mc-mods/plonk/files/3299406).

For 1.7.10 and 1.12.2 there's the `unplaceableItems` config inside `config/plonk.cfg`.

For 1.14.4, 1.15.2 and 1.16.x there's:
- The `unplaceableItems` config inside `saves/<save name>/serverconfig/plonk-server.toml` or `<world folder>/serverconfig/plonk-server.toml`. Copy into `defaultconfigs` folder for modpacks developers.
- The `plonk:unplaceable` item tag for mod developers and data packs. Also for modpack developers too.
